### ISSUE TITLE
'Gender' field not being fetched in the Lab Test form

### ISSUE THREAD

**Issue by deepakc21** [earthians/marley#134]
Issue: Gender field not being fetched in the Lab Test form. 

Steps to reproduce the bug: 
1) Click on 'Lab Test' in the Laboratory function.
2) Click on 'Add Lab Test'.
3) Enter 'Test Template' and 'Patient' information.

Actual result:  
1) Warning/message pops up - App healthcare is not installed
Failed to get method for command healthcare.healthcare.doctype.patient.patient.get_patient_detail with App healthcare is not installed (This bug is already reported - https://github.com/frappe/health/issues/131)
2) Close the warning message and click on 'Save'. A warning/message again pops up - Mandatory fields required in Lab Test  - 'Gender'
![health](https://user-images.githubusercontent.com/97949896/187363904-4cfb6e2e-0b98-4309-bc6f-832f47c802f6.jpg)

**Comment by akurungadam** [comment]
Hello @deepakc21, this is because `get_patient_detail` didn't run as mentioned in your other [issue](https://github.com/frappe/health/issues/131) I'm not sure how this can happen but this shouldn't be the case as healthcare is a module in version-13 and is a separate app only in version-14. Will check, and update you. Thanks for reporting

**Comment by akurungadam** [comment]
Hi @deepakc21 if this site is hosted on frappecloud i think it should be fixed now. I've a test version-13 bench which is not showing this error after removing healthcare app and then restarting the bench. Doesn't look like it has something to do with the app, but will investigate once again

**Comment by deepakc21** [comment]
Hi @akurungadam I cleared cache and tried again but error still persists. I don't have access to the core files as they are hosted on Frappe cloud so I cannot invesitgate whether installation and uninstallation of "Health" app caused these errors. 
![univ](https://user-images.githubusercontent.com/97949896/196611927-35a663bb-90da-466e-ba77-25a503a1dc94.jpg)
![univ1](https://user-images.githubusercontent.com/97949896/196611944-e078894c-e37a-41ff-96df-9113b0520136.jpg)

**Comment by akurungadam** [comment]
I too have faced this, and communicated to frappecloud Team. They are also troubleshooting this. Will post as I get any info. I've also requested not to make Frappe Health available on version-13 benches.  BTW, did you get to restart the bench as I was suggesting?

**Comment by deepakc21** [comment]
I tried but I can't find any option to restart the bench.
![univ2](https://user-images.githubusercontent.com/97949896/196618278-f4590994-c7d6-4c29-b88f-088cc689b433.jpg)
![univ3](https://user-images.githubusercontent.com/97949896/196618293-0d0037a8-09e9-4349-b5fc-a23779d0bbdd.jpg)

**Comment by akurungadam** [comment]
sorry for not coming back on this any earlier, but could you please check if this is resolved now?

**Comment by deepakc21** [comment]
Hello Anoop, I couldn't get it resolved. My 2 sites on frappe cloud had the same issue.
1) For the first site, I had no option but to update to ERPnext v-14 and reinstall health module. I lost my patients data in the transition. 
2) For the second site, I tried upgrading to ERPnext v-14 but the system just couldn't upgrade. Found out that an "[POSawesome](https://frappecloud.com/marketplace/apps/posawesome)" caused irreparable damage to my site. The education and health module stopped functioning. I had to reinstall the "POSawesome" app to start the site so that I can atleast download the data in .csv format and upload them in a fresh site. 

Please feel free to close this bug if there are no further actions required.

**Comment by akurungadam** [comment]
Hi Deepak, thanks for coming back. Sorry about the data loss (hope you had backups) and other hurdles, Frappe Cloud Team has already stopped allowing installation of healthcare app on version-13 benches.  Also, if you need assistance migrating healthcare enabled sites to version-14 do post here.

If anyone else is facing this issue on custom version-13 benches on FC, removing health app from the bench and restarting the bench should fix this.

**Comment by deepakc21** [comment]
Thank you for all the help @akurungadam . There were no backups but Frappe team restored the site so that I could download the data and upload them in the new site. 
Please feel free to close this bug.
